name: tailscale-oidc

permissions:
  id-token: write # This is required for requesting the JWT
  contents: read # This is required for actions/checkout

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '*'

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest, windows-11-arm]
        cache: ['false', 'true']
    runs-on: ${{ matrix.os }}
    steps:
      - name: Check out code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Tailscale Action
        uses: ./
        with:
          oidc-client-id: ${{ secrets.TS_OIDC_CLIENT_ID }}
          oidc-aud-claim: ${{ secrets.TS_OIDC_AUD_CLAIM }}
          tags: tag:ci
          tailnet: ${{ secrets.TS_TAILNET_NAME }}
          use-cache: ${{ matrix.cache }}

      - name: check for tailscale connection
        shell: bash
        run:
          tailscale status -json | jq -r .BackendState | grep -q Running

      - name: ensure no dirty files from Tailscale Action remain
        shell: bash
        run: |
          extra_files=$(git ls-files . --exclude-standard --others)
          if [ ! -z "$extra_files" ]; then
            echo "::error::Unexpected extra files: $extra_files"
            exit 1
          fi

